### ISSUE TITLE
More implementation about coremark-minimal

### ISSUE THREAD

**Issue by clearloop** [wasm3/wasm-coremark#2]
Hi @vshymanskyy, we just wrote some [code][0] for running the `coremark-minimal.wasm` using `wasmtime` and `wasmi`, ping me if it is welcome for pulling request the code into this repo.

It would be nice if there is more explanation about the result `f32` in coremark-minimal ; >

[0]: https://github.com/patractlabs/wasmi-coremark

**Comment by vshymanskyy** [comment]
wasmtime results look weird. I'll try to reproduce

**Comment by vshymanskyy** [comment]
@clearloop Please read this: https://github.com/eembc/coremark#log-file-format
This benchmark should take 12..20 seconds. The `coremark-minimal` does not produce the text output, just the final test result.

One more note: there's no need to run CoreMark multiple times, perform averaging, etc.
When reporting results, it's important to include the system details like CPU model and speed, RAM speed, etc.

**Comment by vshymanskyy** [comment]
I'm trying to run `target/debug/bm wasmitime`, but it exits immediately.

One more note: there's no need to run CoreMark multiple times, perform averaging, etc.

**Comment by vshymanskyy** [comment]
On my machine:
```sh
cargo run --release
./target/release/bm wasmi
...
314.14435
```
I think your `wasmi` result is underestimated. Please re-run in `release` mode.

**Comment by vshymanskyy** [comment]
I tried running WASI build using wasmtime, and unfortunately it freezes:
```sh
# wasmtime 0.25.0
wasmtime run coremark.wasm
...
```

Created a ticket: https://github.com/bytecodealliance/wasmtime/issues/2737

**Comment by vshymanskyy** [comment]
@clearloop looks like the sctipt is misinterpreting the `wasmtime result`.
`1185203011` => raw `0x46A4C343` => which can be treated as f32 `21089.6`

In other words, you should use this to convert res to f32:
```rust
f32::from_bits(res)
```

**Comment by vshymanskyy** [comment]
@clearloop it would be cool to include `wasm3` in the same test script, using [`wasm3-rs`](https://github.com/Veykril/wasm3-rs)

**Comment by clearloop** [comment]
> wasmtime results look weird. I'll try to reproduce

I think it's weird too, but I don't know why LOL


> @clearloop looks like the script is misinterpreting the `wasmtime result`.
> `1185203011` => raw `0x46A4C343` => which can be treated as f32 `21089.6`
> 
> In other words, you should use this to convert res to f32:
> 
> ```rust
> f32::from_bits(res)
> ```

Thanks!!!

> When reporting results, it's important to include the system details like CPU model and speed, RAM speed, etc.

Thanks for your advice, actually I don't know include what system details now ~


> @clearloop it would be cool to include `wasm3` in the same test script, using [`wasm3-rs`](https://github.com/Veykril/wasm3-rs)

I'll do it~ I can add wasmer to it as well

**Comment by vshymanskyy** [comment]
@clearloop here's a PR: https://github.com/patractlabs/wasm-coremark/pull/1

**Comment by clearloop** [comment]
Hi @vshymanskyy, I'm closing this issue since we have added wasm3 coremark in [patractlabs/wasm-coremark][0], that repo terms to prove that `wasm3` is better than `wasmi` haha, it's really awesome, you did a great job!

[0]: https://github.com/patractlabs/wasm-coremark

**Comment by vshymanskyy** [comment]
Thanks! I'll add a link to your repo to the main readme.
